name = "KOVO PUBLICA"
client_id = "23fbda83063d6cb677699efeb2cacab0"
application_url = "https://kovo.services"
embedded = false

[access_scopes]
scopes = "read_analytics,read_customers,read_fulfillments,write_fulfillments,write_inventory,read_inventory,read_locations,read_orders,write_orders,read_products,write_products,read_reports,read_shipping"

[auth]
redirect_urls = ["https://kovo.services/api/shopify/callback"]

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://kovo.services/webhooks"
